# Generated by Django 5.2.1 on 2026-07-06 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('adhaar_no', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('qualification', models.CharField(blank=True, max_length=250, null=True)),
                ('joining_date', models.DateField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='SubstituteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel')),
                ('absent_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_assignments', to='teacher.teacher')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_assignments', to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherYearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel')),
            ],
            options={
                'unique_together': {('teacher', 'year_level')},
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='year_levels',
            field=models.ManyToManyField(through='teacher.TeacherYearLevel', to='director.yearlevel'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['is_active'], name='teacher_is_acti_cdfa14_idx'),
        ),
    ]
