# Generated by Django 5.2.1 on 2025-07-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pan_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
