# Generated by Django 5.2.1 on 2025-08-28 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0008_expensecategory_incomecategory_and_more'),
        ('teacher', '0003_teacherattendance_teacher_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstituteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('absent_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_assignments', to='teacher.teacher')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_assignments', to='teacher.teacher')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel')),
            ],
        ),
    ]
