# Generated by Django 5.2.1 on 2025-06-24 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='guardian',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='student.guardian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='student',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='student.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='year_level',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='director.yearlevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankingdetail',
            name='user',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classperiod',
            name='teacher',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.guardian'),
        ),
        migrations.AddField(
            model_name='document',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
        migrations.AddField(
            model_name='document',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='student',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officestaff',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='managed_by_staff', to='student.student'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='managed_by_staff', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
