# Generated by Django 5.2.1 on 2026-07-06 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.guardian'),
        ),
        migrations.AddField(
            model_name='admission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student'),
        ),
        migrations.AddField(
            model_name='appliedfeediscount',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appliedfeediscount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='student.studentyearlevel'),
        ),
        migrations.AddField(
            model_name='bankingdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankingdetail',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='director.bankname'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='director.city'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_periods', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.classroom'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.classroomtype'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='director.country'),
        ),
        migrations.AddField(
            model_name='director',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.guardian'),
        ),
        migrations.AddField(
            model_name='document',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
        migrations.AddField(
            model_name='document',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_types',
            field=models.ManyToManyField(to='director.documenttype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.employee'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.examtype'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.examtype'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appliedfeediscount',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.feestructure'),
        ),
        migrations.AddField(
            model_name='file',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='director.document'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='master_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='director.masterfee'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='admissions',
            field=models.ManyToManyField(blank=True, related_name='handled_by_staff', to='director.admission'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.department'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='managed_by_staff', to='student.student'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='managed_by_staff', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='office_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.officestaff'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.payment'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='end_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_time', to='director.period'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='start_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='start_time', to='director.period'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentyearlevel'),
        ),
        migrations.AddField(
            model_name='schoolexpense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolexpense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='director.expensecategory'),
        ),
        migrations.AddField(
            model_name='schoolexpense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolexpense',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.payment'),
        ),
        migrations.AddField(
            model_name='schoolincome',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='director.incomecategory'),
        ),
        migrations.AddField(
            model_name='schoolincome',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolturnover',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolturnover',
            name='school_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='director.schoolyear'),
        ),
        migrations.AddField(
            model_name='schoolincome',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='director.schoolyear'),
        ),
        migrations.AddField(
            model_name='schoolexpense',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.schoolyear'),
        ),
        migrations.AddField(
            model_name='period',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.schoolyear'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.schoolyear'),
        ),
        migrations.AddField(
            model_name='admission',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.schoolyear'),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.state'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='director.state'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='director.feestructure'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.schoolyear'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='student_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='student.studentyearlevel'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='director.studentfee'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.department'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.subject'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.subject'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.subject'),
        ),
        migrations.AddField(
            model_name='term',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.schoolyear'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.term'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.term'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.term'),
        ),
        migrations.AddField(
            model_name='yearlevel',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='year_levels', to='director.masterfee'),
        ),
        migrations.AddField(
            model_name='subject',
            name='year_levels',
            field=models.ManyToManyField(related_name='subjects', to='director.yearlevel'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='year_level',
            field=models.ManyToManyField(related_name='fee_structures', to='director.yearlevel'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.yearlevel'),
        ),
        migrations.AddField(
            model_name='admission',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.yearlevel'),
        ),
        migrations.AddIndex(
            model_name='bankingdetail',
            index=models.Index(fields=['is_active'], name='BankingDeta_is_acti_feae5a_idx'),
        ),
        migrations.AddIndex(
            model_name='director',
            index=models.Index(fields=['is_active'], name='Director_is_acti_55aaef_idx'),
        ),
        migrations.AddIndex(
            model_name='officestaff',
            index=models.Index(fields=['is_active'], name='OfficeStaff_is_acti_af84e3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_active'], name='Document_is_acti_caee60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolincome',
            unique_together={('category', 'month', 'school_year')},
        ),
        migrations.AlterUniqueTogether(
            name='employeesalary',
            unique_together={('user', 'month', 'school_year')},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_active'], name='Address_is_acti_70bc7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('student_year', 'fee_structure', 'month', 'school_year')},
        ),
        migrations.AlterUniqueTogether(
            name='exampaper',
            unique_together={('exam_type', 'subject', 'year_level', 'term')},
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['is_active'], name='Admission_is_acti_5ce93c_idx'),
        ),
    ]
