# Generated by Django 5.2.1 on 2026-07-23 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='school_year',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='director.schoolyear'),
        ),
        migrations.AddField(
            model_name='yearlevel',
            name='max_section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(choices=[('Admission Fee', 'Admission Fee'), ('Exam Fee', 'Exam Fee'), ('Tuition Fee', 'Tuition Fee'), ('Caution Fee', 'Caution Fee'), ('Maintenance', 'Maintenance'), ('Form Fee', 'Form Fee'), ('Annual Charges', 'Annual Charges'), ('Others', 'Others')], max_length=100),
        ),
    ]
