# Generated by Django 5.2.1 on 2025-07-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_address_user_admission_guardian_admission_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='emergency_contact_n0',
            new_name='emergency_contact_no',
        ),
        migrations.RemoveField(
            model_name='address',
            name='word_no',
        ),
        migrations.RemoveField(
            model_name='feerecord',
            name='signature',
        ),
        migrations.AddField(
            model_name='address',
            name='ward_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='received_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='area_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='habitation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
