# Generated by Django 5.2.1 on 2026-09-11 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_feestructure_school_year_yearlevel_max_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='director.schoolyear'),
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('class_name', 'term', 'exam_type', 'subject')},
        ),
    ]
