# Generated by Django 5.2.1 on 2025-07-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_rename_emergency_contact_n0_admission_emergency_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='year_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.yearlevel'),
        ),
    ]
