# Generated by Django 5.2.1 on 2025-07-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_admission_enrollment_no_alter_admission_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officestaff',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='officestaff',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
