# Generated by Django 5.2.1 on 2025-08-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0005_alter_officestaff_gender_alter_officestaff_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='is_rte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='rte_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
