# Generated by Django 5.2.1 on 2025-08-28 06:12

import director.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0006_admission_is_rte_admission_rte_number'),
        ('student', '0002_student_contact_number_student_roll_number_and_more'),
        ('teacher', '0002_alter_teacher_pan_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paper_code', models.CharField(max_length=7, unique=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=director.utils.ExamPaper_folder)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_fee_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tuition_fee_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NonScholasticGradeTermWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSocialQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSocialQualityTermWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('grade', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('attendance', models.CharField(blank=True, max_length=10, null=True)),
                ('teacher_remark', models.TextField()),
                ('supplementary_in', models.CharField(blank=True, max_length=100, null=True)),
                ('school_reopen_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportCardDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bankingdetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='year_level',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='director.yearlevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_periods', to='teacher.teacher'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_active'], name='Address_is_acti_70bc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='bankingdetail',
            index=models.Index(fields=['is_active'], name='BankingDeta_is_acti_feae5a_idx'),
        ),
        migrations.AddIndex(
            model_name='director',
            index=models.Index(fields=['is_active'], name='Director_is_acti_55aaef_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_active'], name='Document_is_acti_caee60_idx'),
        ),
        migrations.AddIndex(
            model_name='officestaff',
            index=models.Index(fields=['is_active'], name='OfficeStaff_is_acti_af84e3_idx'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.subject'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.term'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.subject'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.term'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.examtype'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.examtype'),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_info', to='student.student'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='discounted_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.feediscount'),
        ),
        migrations.AddIndex(
            model_name='feerecord',
            index=models.Index(fields=['is_active'], name='FeeRecord_is_acti_3c8bc5_idx'),
        ),
        migrations.AddField(
            model_name='nonscholasticgradetermwise',
            name='non_scholastic_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_grades', to='director.subject'),
        ),
        migrations.AddField(
            model_name='nonscholasticgradetermwise',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.term'),
        ),
        migrations.AddField(
            model_name='personalsocialqualitytermwise',
            name='personal_quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_grades', to='director.personalsocialquality'),
        ),
        migrations.AddField(
            model_name='personalsocialqualitytermwise',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.term'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='promoted_to_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportcards_as_promotion', to='student.studentyearlevel'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentyearlevel'),
        ),
        migrations.AddField(
            model_name='personalsocialqualitytermwise',
            name='report_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_qualities', to='director.reportcard'),
        ),
        migrations.AddField(
            model_name='nonscholasticgradetermwise',
            name='report_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='non_scholastic_grades', to='director.reportcard'),
        ),
        migrations.AddField(
            model_name='reportcarddocument',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_card_documents', to='director.document'),
        ),
        migrations.AddField(
            model_name='reportcarddocument',
            name='report_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='director.reportcard'),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.examtype'),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentyearlevel'),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.subject'),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.term'),
        ),
        migrations.AddField(
            model_name='subjectscore',
            name='marks_obtained',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='director.studentmarks'),
        ),
        migrations.AddField(
            model_name='subjectscore',
            name='report_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='director.reportcard'),
        ),
        migrations.AlterUniqueTogether(
            name='exampaper',
            unique_together={('exam_type', 'subject', 'year_level')},
        ),
        migrations.AlterUniqueTogether(
            name='personalsocialqualitytermwise',
            unique_together={('report_card', 'personal_quality', 'term', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='nonscholasticgradetermwise',
            unique_together={('report_card', 'non_scholastic_subject', 'term', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='studentmarks',
            unique_together={('student', 'exam_type', 'term', 'subject')},
        ),
    ]
