# Generated by Django 5.2.1 on 2026-07-06 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'GuardianType',
                'verbose_name_plural': 'GuardianTypes',
                'db_table': 'GuardianType',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('annual_income', models.IntegerField(blank=True, null=True)),
                ('means_of_livelihood', models.CharField(blank=True, max_length=15, null=True)),
                ('qualification', models.CharField(blank=True, max_length=300, null=True)),
                ('occupation', models.CharField(blank=True, max_length=300, null=True)),
                ('designation', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_relation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'db_table': 'Guardian',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=250, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('number_of_siblings', models.IntegerField(blank=True, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('scholar_number', models.CharField(blank=True, max_length=50, null=True)),
                ('classes', models.ManyToManyField(related_name='Student', to='director.classperiod')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentguardian', to='student.guardian')),
                ('guardian_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.guardiantype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
            ],
            options={
                'verbose_name': 'StudentGuardian',
                'verbose_name_plural': 'StudentGuardians',
                'db_table': 'StudentGuardian',
            },
        ),
        migrations.CreateModel(
            name='StudentYearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.yearlevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_year_levels', to='student.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.schoolyear')),
            ],
            options={
                'verbose_name': 'StudentYearLevel',
                'verbose_name_plural': 'StudentYearLevels',
                'db_table': 'StudentYearLevel',
            },
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['is_active'], name='Guardian_is_acti_8b99d8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='Student_is_acti_74a94b_idx'),
        ),
    ]
