# Generated by Django 5.2.1 on 2025-08-28 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0007_exampaper_examschedule_examtype_feediscount_and_more'),
        ('student', '0002_student_contact_number_student_roll_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentguardian',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentguardian', to='student.guardian'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['is_active'], name='Guardian_is_acti_8b99d8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='Student_is_acti_74a94b_idx'),
        ),
    ]
